# Generated by Django 4.2 on 2025-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=25)),
                ('instructor', models.CharField(max_length=25)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrolled_classes', models.ManyToManyField(related_name='clients', to='bookings.classlist')),
            ],
        ),
    ]
